name=str(input("Name: "))
mobile_number=int(input("Mobile Number: "))
mail_id=input("Mail-id: ")
college_name=input("College Name: ")
branch=input("Branch: ")
print("###Student_profile###")
print(".....................")
print("Student Name is ",name)
print("Mobile Number is ",mobile_number)
print("Mail-id is ",mail_id)
print("College Name is",college_name)
print("Branch is ",branch)
